import { Category, Product } from "./types";

export const categories: Category[] = [
  {
    id: "cat-mehndi-cones",
    name: "Mehndi Cones",
    slug: "mehndi-cones",
    blurb: "Natural & instant henna cones, hand-rolled fresh.",
  },
  {
    id: "cat-instant",
    name: "Instant Products",
    slug: "instant-products",
    blurb: "Instant nail henna and dipper henna for quick colour.",
  },
  {
    id: "cat-stencils",
    name: "Stencils",
    slug: "stencils",
    blurb: "Reusable mehndi stencils, from kids' sizes to full bridal hands.",
  },
  {
    id: "cat-powders",
    name: "Powders & Hair Care",
    slug: "powders-hair-care",
    blurb: "Herbal hair colour powders, ubtan, wax and hair masala.",
  },
  {
    id: "cat-skincare",
    name: "Skincare",
    slug: "skincare",
    blurb: "Handmade soaps for every skin concern.",
  },
  {
    id: "cat-fragrance",
    name: "Fragrance & Lifestyle",
    slug: "fragrance-lifestyle",
    blurb: "Chai masala, oudh sticks, lip balms and everyday indulgences.",
  },
];

// NOTE: image paths point at /products/<slug>.jpg — drop real product photography
// into /public/products/ using these filenames (see README "Adding product photos").
//
// This array is the ONE-TIME SEED for the persisted product store (data/products.json,
// managed in src/lib/db.ts). After first run, the admin panel's product CRUD reads and
// writes data/products.json — editing stock/price/etc. there, not here. To reset the
// catalog back to this seed data, delete data/products.json and restart the dev server.
export const seedProducts: Product[] = [
  // Mehndi Cones
  {
    id: "p-natural-box-12",
    name: "Natural Henna Cone Box (12 pcs)",
    slug: "natural-henna-cone-box-12",
    description:
      "A box of 12 hand-rolled natural henna cones, made from finely sifted henna leaves for a deep, long-lasting stain. Free from added chemicals — the traditional way mehndi should be.",
    price: 240,
    images: ["/products/real/natural-cone-1.jpg"],
    categorySlug: "mehndi-cones",
    variantLabel: "12 pcs",
    stock: 40,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "p-natural-box-2",
    name: "Natural Henna Cone Box (2 boxes)",
    slug: "natural-henna-cone-box-2-boxes",
    description:
      "Two boxes of our natural henna cones — enough to share, or to keep your festive season fully stocked. Each cone is hand-rolled for smooth, even application.",
    price: 400,
    images: ["/products/real/natural-cone-1.jpg"],
    categorySlug: "mehndi-cones",
    variantLabel: "2 boxes",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-instant-box-12",
    name: "Instant Henna Cone Box (12 pcs)",
    slug: "instant-henna-cone-box-12",
    description:
      "12 instant henna cones formulated to darken quickly, perfect for last-minute functions and everyday wear when you don't have hours to wait.",
    price: 240,
    images: ["/products/real/instant-mehndi-box-1.jpg"],
    categorySlug: "mehndi-cones",
    variantLabel: "12 pcs",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-instant-box-2",
    name: "Instant Henna Cone Box (2 boxes)",
    slug: "instant-henna-cone-box-2-boxes",
    description:
      "Two boxes of our fast-darkening instant henna cones, for households and small mehndi setups that go through cones quickly.",
    price: 400,
    images: ["/products/real/instant-mehndi-box-1.jpg"],
    categorySlug: "mehndi-cones",
    variantLabel: "2 boxes",
    stock: 28,
    isActive: true,
  },
  {
    id: "p-nail-natural-cone",
    name: "Nail Natural Cone",
    slug: "nail-natural-cone",
    description:
      "A small natural henna cone sized for nail art and fine detailing, giving you precise control over delicate designs.",
    price: 20,
    images: ["/products/real/nail-natural-cone-real.jpg"],
    categorySlug: "mehndi-cones",
    stock: 100,
    isActive: true,
  },
  {
    id: "p-bridal-hand-cone",
    name: "Bridal Hand Cone",
    slug: "bridal-hand-cone",
    description:
      "Our finest natural henna, rolled specifically for bridal detailing — a fine tip for intricate lines and a deep, rich stain that lasts through the celebrations.",
    price: 50,
    images: ["/products/real/bridal-cone-real.jpg"],
    categorySlug: "mehndi-cones",
    stock: 60,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "p-red-instant-pakistani",
    name: "Red Instant Pakistani Henna",
    slug: "red-instant-pakistani-henna",
    description:
      "A red-toned instant henna cone in the Pakistani style, known for its warm reddish stain and smooth, fast-flowing paste.",
    price: 40,
    images: ["/products/mehndi-cones.svg"],
    categorySlug: "mehndi-cones",
    stock: 70,
    isActive: true,
  },
  {
    id: "p-aftercare-oil",
    name: "After-Care Oil",
    slug: "after-care-oil",
    description:
      "A light henna after-care oil to seal in colour once your mehndi paste has dried — helps deepen and extend the stain.",
    price: 80,
    images: ["/products/real/after-care-oil.jpeg"],
    categorySlug: "mehndi-cones",
    stock: 50,
    isActive: true,
  },

  // Instant Products
  {
    id: "p-instant-nail-polish-henna",
    name: "Instant Nail Polish Henna",
    slug: "instant-nail-polish-henna",
    description:
      "Instant henna in a nail-polish-style applicator for quick, mess-free colour on nails. Available in Red, Maroon and Brown.",
    price: 100,
    images: ["/products/real/instant-nail-polish-henna-real.jpg"],
    categorySlug: "instant-products",
    variantLabel: "Red / Maroon / Brown",
    stock: 60,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "p-instant-nail-polish-henna-2",
    name: "Instant Nail Polish Henna (2 pieces)",
    slug: "instant-nail-polish-henna-2-pieces",
    description:
      "Two instant nail-polish henna applicators, so you always have a backup colour on hand.",
    price: 170,
    images: ["/products/real/instant-nail-polish-henna.jpeg"],
    categorySlug: "instant-products",
    variantLabel: "2 pieces",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-dipper-instant-henna",
    name: "Dipper Instant Henna",
    slug: "dipper-instant-henna",
    description:
      "A dip-and-go instant henna in a compact bottle, ideal for quick touch-ups on hands, feet or nails.",
    price: 80,
    images: ["/products/real/dipper-instant-henna.jpeg"],
    categorySlug: "instant-products",
    stock: 55,
    isActive: true,
  },
  {
    id: "p-dipper-instant-henna-2",
    name: "Dipper Instant Henna (2 pieces)",
    slug: "dipper-instant-henna-2-pieces",
    description: "Two dipper-style instant henna bottles for everyday quick colour.",
    price: 120,
    images: ["/products/real/dipper-instant-henna.jpeg"],
    categorySlug: "instant-products",
    variantLabel: "2 pieces",
    stock: 35,
    isActive: true,
  },

  // Stencils
  {
    id: "p-stencil-medium",
    name: "Mehndi Stencil — Medium",
    slug: "mehndi-stencil-medium",
    description:
      "A reusable medium-sized mehndi stencil for quick, even designs on the back of the hand — great for beginners and busy mornings.",
    price: 100,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Medium",
    stock: 50,
    isActive: true,
  },
  {
    id: "p-stencil-medium-2",
    name: "Mehndi Stencil — Medium (2 pieces)",
    slug: "mehndi-stencil-medium-2-pieces",
    description: "Two medium stencils so you can design both hands together.",
    price: 180,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Medium x2",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-stencil-large",
    name: "Mehndi Stencil — Large",
    slug: "mehndi-stencil-large",
    description: "A large stencil for a fuller, more elaborate coverage across the palm and hand.",
    price: 120,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Large",
    stock: 45,
    isActive: true,
  },
  {
    id: "p-stencil-large-2",
    name: "Mehndi Stencil — Large (2 pieces)",
    slug: "mehndi-stencil-large-2-pieces",
    description: "Two large stencils, for both hands or for sharing.",
    price: 200,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Large x2",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-stencil-fingers",
    name: "Mehndi Stencil — Fingers",
    slug: "mehndi-stencil-fingers",
    description: "Finger-only stencils for delicate detailing without covering the whole hand.",
    price: 60,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Fingers",
    stock: 55,
    isActive: true,
  },
  {
    id: "p-stencil-fingers-2",
    name: "Mehndi Stencil — Fingers (2 pieces)",
    slug: "mehndi-stencil-fingers-2-pieces",
    description: "Two finger stencils for matching detail on both hands.",
    price: 100,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Fingers x2",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-stencil-kids",
    name: "Mehndi Stencil — Kids",
    slug: "mehndi-stencil-kids",
    description: "Simple, fun stencil designs sized for little hands.",
    price: 40,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Kids",
    stock: 60,
    isActive: true,
  },
  {
    id: "p-stencil-kids-3",
    name: "Mehndi Stencil — Kids (3 pieces)",
    slug: "mehndi-stencil-kids-3-pieces",
    description: "A set of three kids' stencils with a mix of playful designs.",
    price: 100,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Kids x3",
    stock: 35,
    isActive: true,
  },
  {
    id: "p-stencil-bridal-full",
    name: "Bridal Full Hands Stencil",
    slug: "bridal-full-hands-stencil",
    description:
      "A comprehensive stencil set covering the full hand and forearm for a complete bridal look, guided and even.",
    price: 400,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Full Hands",
    stock: 20,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "p-stencil-semi-bridal",
    name: "Semi Bridal Stencil",
    slug: "semi-bridal-stencil",
    description: "A lighter bridal coverage stencil for engagements, showers and pre-wedding functions.",
    price: 250,
    images: ["/products/real/stencils.jpeg"],
    categorySlug: "stencils",
    variantLabel: "Semi Bridal",
    stock: 25,
    isActive: true,
  },

  // Powders & Hair Care
  {
    id: "p-ubtan",
    name: "Ubtan Powder (50g + 25g free)",
    slug: "ubtan-powder-50g-25g-free",
    description:
      "A traditional herbal ubtan blend for a natural glow, with a bonus 25g on every 50g pack.",
    price: 120,
    images: ["/products/real/ubtan-powder-real.jpg"],
    categorySlug: "powders-hair-care",
    variantLabel: "50g + 25g free",
    stock: 45,
    isActive: true,
  },
  {
    id: "p-wax-powder",
    name: "Wax Powder Hair Remover",
    slug: "wax-powder-hair-remover",
    description: "A herbal wax powder formulated to gently remove unwanted hair at home.",
    price: 120,
    images: ["/products/real/wax-powder-real.jpg"],
    categorySlug: "powders-hair-care",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-hair-powder-black",
    name: "Herbal Hair Colour Powder — Black",
    slug: "herbal-hair-powder-black",
    description: "A herbal hair colour mix in Black, blended from traditional botanicals.",
    price: 200,
    images: ["/products/real/hair-henna-black-real.jpg"],
    categorySlug: "powders-hair-care",
    variantLabel: "Black",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-hair-powder-brown",
    name: "Herbal Hair Colour Powder — Brown",
    slug: "herbal-hair-powder-brown",
    description: "A herbal hair colour mix in Brown, blended from traditional botanicals.",
    price: 200,
    images: ["/products/real/hair-henna-brown-real.jpg"],
    categorySlug: "powders-hair-care",
    variantLabel: "Brown",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-hair-powder-burgundy",
    name: "Herbal Hair Colour Powder — Burgundy",
    slug: "herbal-hair-powder-burgundy",
    description: "A herbal hair colour mix in Burgundy, blended from traditional botanicals.",
    price: 200,
    images: ["/products/real/hair-henna-burgundy-real.jpg"],
    categorySlug: "powders-hair-care",
    variantLabel: "Burgundy",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-hair-masala",
    name: "Hair Masala",
    slug: "hair-masala",
    description: "A nourishing herbal hair masala blend to strengthen and condition from root to tip.",
    price: 150,
    images: ["/products/real/hair-masala.jpg"],
    categorySlug: "powders-hair-care",
    stock: 35,
    isActive: true,
  },

  // Lip Care (folded into Fragrance & Lifestyle in nav, but kept distinguishable via search)
  {
    id: "p-lip-balm-strawberry",
    name: "Strawberry Lip Balm",
    slug: "strawberry-lip-balm",
    description: "A softening lip balm with a light strawberry finish for everyday care.",
    price: 120,
    images: ["/products/real/lip-balms.jpeg"],
    categorySlug: "fragrance-lifestyle",
    variantLabel: "Strawberry",
    stock: 50,
    isActive: true,
  },
  {
    id: "p-lip-balm-beetroot",
    name: "Beetroot Lip Balm",
    slug: "beetroot-lip-balm",
    description: "A nourishing lip balm tinted naturally with beetroot for soft, healthy-looking lips.",
    price: 120,
    images: ["/products/real/lip-balms.jpeg"],
    categorySlug: "fragrance-lifestyle",
    variantLabel: "Beetroot",
    stock: 50,
    isActive: true,
  },

  // Fragrance & Lifestyle
  {
    id: "p-royal-chai-masala",
    name: "Royal Chai Masala (25g)",
    slug: "royal-chai-masala-25g",
    description: "A warming, aromatic chai masala blend to elevate your everyday cup.",
    price: 100,
    images: ["/products/fragrance-lifestyle.svg"],
    categorySlug: "fragrance-lifestyle",
    variantLabel: "25g",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-oudh-sticks",
    name: "Oudh Sticks Box (100g)",
    slug: "oudh-sticks-box-100g",
    description: "A box of fragrant oudh incense sticks for a warm, traditional atmosphere at home.",
    price: 100,
    images: ["/products/fragrance-lifestyle.svg"],
    categorySlug: "fragrance-lifestyle",
    variantLabel: "100g",
    stock: 40,
    isActive: true,
  },

  // Skincare
  {
    id: "p-soap-multani-mitti",
    name: "Multani Mitti Soap",
    slug: "multani-mitti-soap",
    description: "A handmade soap with Multani Mitti (Fuller's Earth) to gently cleanse and refresh skin.",
    price: 200,
    images: ["/products/real/multani-mitti-soap-real.jpg"],
    categorySlug: "skincare",
    stock: 40,
    isFeatured: true,
    isActive: true,
  },
  {
    id: "p-soap-goat-milk",
    name: "Goat Milk Soap",
    slug: "goat-milk-soap",
    description: "A creamy, moisturising handmade soap enriched with goat milk.",
    price: 200,
    images: ["/products/real/goat-milk-soap-real.jpg"],
    categorySlug: "skincare",
    stock: 40,
    isActive: true,
  },
  {
    id: "p-soap-anti-acne",
    name: "Anti-Acne Haldi Chandan Soap",
    slug: "anti-acne-haldi-chandan-soap",
    description: "A turmeric and sandalwood soap formulated for acne-prone skin.",
    price: 200,
    images: ["/products/real/haldi-chandan-soap-real.jpg"],
    categorySlug: "skincare",
    stock: 35,
    isActive: true,
  },
  {
    id: "p-soap-ubtan",
    name: "Ubtan Soap",
    slug: "ubtan-soap",
    description: "A handmade soap based on our traditional ubtan blend for a natural glow.",
    price: 200,
    images: ["/products/skincare.svg"],
    categorySlug: "skincare",
    stock: 35,
    isActive: true,
  },
  {
    id: "p-soap-skin-lightening",
    name: "Skin Lightening Soap",
    slug: "skin-lightening-soap",
    description: "A gentle handmade soap formulated to even out tone with regular use.",
    price: 200,
    images: ["/products/real/skin-lightening-soap-real.jpg"],
    categorySlug: "skincare",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-soap-charcoal",
    name: "Charcoal Soap",
    slug: "charcoal-soap",
    description: "An activated charcoal soap to draw out impurities and deep-clean skin.",
    price: 200,
    images: ["/products/real/charcoal-soap-real.jpg"],
    categorySlug: "skincare",
    stock: 30,
    isActive: true,
  },
  {
    id: "p-soap-menthol",
    name: "Menthol Soap",
    slug: "menthol-soap",
    description: "A cooling menthol-infused soap for a refreshing everyday wash.",
    price: 200,
    images: ["/products/real/menthol-soap-real.jpg"],
    categorySlug: "skincare",
    stock: 30,
    isActive: true,
  },
];

export function getCategoryBySlug(slug: string) {
  return categories.find((c) => c.slug === slug);
}
